window:
    dimensions:
        columns: 170
        lines: 40

    padding:
        x: 0
        y: 0

    dynamic_title: true
    dynamic_padding: false

    decorations: none

    startup_mode: Windowed

tabspaces: 4
dynamic_title: true

scrolling:
    history: 0

    multiplier: 3

font:
    normal:
        family: Fira Mono for Powerline
        style: Regular

    medium:
        family: Fira Mono for Powerline
        style: Medium

    bold:
        family: Fira Mono for Powerline
        style: Bold

    bold_italic:
        family: Ubuntu Mono derivative Powerline
        style: Bold Italic

    italic:
        family: Ubuntu Mono derivative Powerline
        style: Italic

    size: 12

    offset:
        x: 0
        y: 0

    glyph_offset:
        x: 0
        y: 0

    use_thin_strokes: true

draw_bold_text_with_bright_colors: false

options:
    size: 12
    thin_strokes: true
    antialias: lcd
    hinting: true
    style: Regular

key_bindings:
    - { key: F11, mods: None, action: ToggleFullscreen }

shell:
    program: zsh
    args:
        - -l
        - -c
        - "tmux"

# Colors (Gruvbox dark)
colors:
    primary:
        # hard contrast background - '#1d2021'
        # soft contrast background - '#32302f'
        background: &gruvbox_dark_bg "#1d2021"
        foreground: "#ebdbb2"
        bright_foreground: "#fbf1c7"
    cursor:
        cursor: "#79740e"
    vi_mode_cursor:
        text: CellBackground
        cursor: "#79740e"
    selection:
        text: CellBackground
        background: CellForeground
    bright:
        black: "#928374"
        red: "#fb4934"
        green: "#b8bb26"
        yellow: "#fabd2f"
        blue: "#83a598"
        magenta: "#d3869b"
        cyan: "#8ec07c"
        white: "#ebdbb2"
    normal:
        black: *gruvbox_dark_bg
        red: "#cc241d"
        green: "#98971a"
        yellow: "#d79921"
        blue: "#458588"
        magenta: "#b16286"
        cyan: "#689d6a"
        white: "#ebdbb2"
    dim:
        black: "#32302f"
        red: "#9d0006"
        green: "#79740e"
        yellow: "#b57614"
        blue: "#076678"
        magenta: "#8f3f71"
        cyan: "#427b58"
        white: "#928374"
