ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.1
errorCode = 0
warningCode = 0

[rule.atomic]
[rule.unreachable-code]
[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.if-return]
[rule.increment-decrement]
[rule.var-naming]
[rule.var-declaration]
[rule.range]
[rule.receiver-naming]
[rule.time-naming]
[rule.time-equal]
[rule.unexported-return]
[rule.indent-error-flow]
[rule.errorf]
[rule.unnecessary-stmt]
[rule.get-return]
[rule.modifies-parameter]
[rule.modifies-value-receiver]
[rule.confusing-naming]
[rule.confusing-results]
[rule.add-constant]
[rule.constant-logical-expr]
[rule.range-val-in-closure]
[rule.range-val-address]
[rule.waitgroup-by-value]
[rule.empty-block]
[rule.superfluous-else]
[rule.unused-parameter]
[rule.unused-receiver]
[rule.early-return]
[rule.defer]
[rule.useless-break]
[rule.optimize-operands-order]
[rule.unconditional-recursion]
[rule.identical-branches]
[rule.redefines-builtin-id]
[rule.line-length-limit]
arguments = [100]
